import fs from 'node:fs'
import path from 'node:path'
import story from '../src/data/story.js'

// One story-matched still per illustrated page. Chat and video scenes keep
// their native presentation; no photo insets or slideshow frames are added.
const root = path.resolve(import.meta.dirname, '..')
const photo = name => `./assets/images/${name}`
const selected = {
  intro01: 'lin-phone-natural-v4.webp', intro02: 'lin-final-edit-v3.webp',
  intro03: 'evidence-wall-v5.webp', intro04: 'scene-payment-hover-v7.webp',
  a01b: 'lin-phone-natural-v4.webp', a05: 'liang-deadline-v2.webp',
  a06: 'xu-salary-v5.webp', q01: 'scene-payment-hover-v7.webp',
  b1a: 'lin-final-edit-v3.webp', b1a2: 'lin-message-v2.webp',
  b1a3: 'liang-deadline-v2.webp', b1b: 'scene-payment-hover-v7.webp',
  c05: 'song-receipts-v2.webp', c06: 'sample-confirm.webp',
  c08: 'song-lab.jpg', c09: 'song-lab.jpg', c10: 'sample-confirm.webp',
  c11: 'song-receipts-v2.webp', q02: 'song-receipts-v2.webp',
  b2a3: 'song-lab.jpg', b2b: 'sample-confirm.webp',
  b2b2: 'song-receipts-v2.webp',
  q03c: 'song-lab.jpg', q04intro: 'scene-letter-compare-v7.webp',
  q04: 'scene-letter-compare-v7.webp', q04a: 'archive-motion-02-v1.webp',
  q04b: 'official-replies-01-v1.webp', q05b: 'jiang-consent-v3.webp',
  q06b: 'shen-call.jpg', q07intro: 'delivery-clue-01-v1.webp',
  q07: 'delivery-clue-02-v1.webp', q07a: 'lin-message-v2.webp',
  q08ledger: 'refund-ledger-02-v1.webp', q08: 'refund-ledger-01-v1.webp',
  q08a: 'zhou-refund-v3.webp', q08b: 'refund-ledger-02-v1.webp',
  q09compare: 'fake-video-compare-v1.webp',
  q09a: 'fake-video-compare-v1.webp', q09b: 'lin-fake-video-v3.webp',
  q10a: 'official-replies-02-v1.webp', q10b: 'lin-final-edit-v3.webp',
  m01: 'shen-call.jpg', m01b: 'ai-identity-check-v5.webp',
  m01c: 'shen-call.jpg', m01d: 'verify-official-v2.webp',
  q11consent: 'consent-interview-v5.webp', q12intro: 'lin-final-edit-v3.webp',
  e2: 'official-replies-02-v1.webp', e3: 'lin-final-edit-v3.webp',
  e6: 'fake-video-compare-v1.webp'
}

const replacementVideos = new Set(['a05', 'c06', 'c08', 'c09', 'c10', 'm01', 'q12intro'])
const oldTextCards = new Set(['compare.jpg', 'end.jpg', 'fee.jpg', 'group.jpg', 'money.jpg', 'money2.jpg', 'preserve.jpg', 'q1.jpg', 'q2.jpg', 'safe1.jpg', 'safe2.jpg', 'wait1.jpg', 'wait2.jpg', 'warn.jpg'])
const plan = {}
for (const node of Object.values(story.nodes)) {
  const media = node.media || {}
  if (media.type === 'chat' || (media.type === 'video' && !replacementVideos.has(node.id))) continue
  const src = selected[node.id] ? photo(selected[node.id]) : media.src
  if (!src || oldTextCards.has(path.basename(src))) throw new Error(`Unreviewed visual: ${node.id} -> ${src}`)
  if (!fs.existsSync(path.join(root, src.replace(/^\.\//, '')))) throw new Error(`Missing visual: ${node.id} -> ${src}`)
  plan[node.id] = { type: 'image', src, alt: `${node.heading}的剧情画面` }
}
fs.writeFileSync(path.join(root, 'src', 'data', 'page-visuals.js'), `// Generated by scripts/build_page_visuals.mjs. One story-matched still per illustrated page.\nexport const pageVisuals = ${JSON.stringify(plan, null, 2)}\n`)
console.log(`Mapped ${Object.keys(plan).length} illustrated pages to single stills.`)
